[profile.release]
opt-level = 3
debug = false
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
debug = true
incremental = true

[net]
git-fetch-with-cli = true

[cargo-new]
edition = "2024"
