name: Build macOS x86_64

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build macOS x86_64
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        run: |
          rustup default stable
          rustup target add x86_64-apple-darwin
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: shared-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: shared-cargo-
      
      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: shared-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: shared-target-
      
      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-apple-darwin --verbose
      
      - name: Strip Binary
        run: |
          strip target/x86_64-apple-darwin/release/ovc
      
      - name: Prepare Binary
        run: |
          cp target/x86_64-apple-darwin/release/ovc ovc-macos-x86_64
          chmod +x ovc-macos-x86_64
      
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovc-macos-x86_64
          path: ovc-macos-x86_64 