name: Build Linux x86_64

on:
  workflow_call:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86_64:
    name: Build Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust and targets
        run: |
          rustup default stable
          rustup target add x86_64-unknown-linux-gnu
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: linux-x86_64-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            linux-x86_64-cargo-
      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: linux-x86_64-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            linux-x86_64-target-
      - name: Check build for target
        run: |
          cargo check --target x86_64-unknown-linux-gnu --verbose
      - name: Build release binary
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu --verbose 