name: Build Linux x86_64

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        run: |
          rustup default stable
          rustup target add x86_64-unknown-linux-gnu
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: linux-x86_64-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: linux-x86_64-cargo-
      
      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: linux-x86_64-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: linux-x86_64-target-
      
      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu --verbose
      
      - name: Strip Binary
        run: |
          strip target/x86_64-unknown-linux-gnu/release/ovc
      
      - name: Prepare Binary
        run: |
          cp target/x86_64-unknown-linux-gnu/release/ovc ovc-linux-x86_64
          chmod +x ovc-linux-x86_64
      
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovc-linux-x86_64
          path: ovc-linux-x86_64 