name: Build Linux ARM64

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Linux ARM64
    runs-on: ubuntu-24.04-arm64
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        run: |
          rustup default stable
          rustup target add aarch64-unknown-linux-gnu
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: shared-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: shared-cargo-
      
      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: shared-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: shared-target-
      
      - name: Build Release Binary
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu --verbose
      
      - name: Strip Binary
        run: |
          strip target/aarch64-unknown-linux-gnu/release/ovc
      
      - name: Prepare Binary
        run: |
          cp target/aarch64-unknown-linux-gnu/release/ovc ovc-linux-arm64
          chmod +x ovc-linux-arm64
      
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovc-linux-arm64
          path: ovc-linux-arm64 