name: Build Linux ARM64

on:
  workflow_call:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-arm64:
    name: Build Linux ARM64
    runs-on: ubuntu-24.04-arm64

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust and targets
        run: |
          rustup default stable
          rustup target add aarch64-unknown-linux-gnu
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: linux-arm64-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            linux-arm64-cargo-
      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: linux-arm64-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            linux-arm64-target-
      - name: Check build for target
        run: |
          cargo check --target aarch64-unknown-linux-gnu --verbose
      - name: Build release binary
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu --verbose 