name: Cache Cleanup

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean up old caches
    runs-on: ubuntu-latest
    permissions:
      actions: write
    
    steps:
      - name: Cleanup old caches
        run: |
          echo "Fetching list of cache keys"
          
          # Get all caches older than 7 days
          cacheKeysToDelete=$(gh cache list --limit 100 --json id,createdAt --jq '
            map(select(
              (.createdAt | fromdateiso8601) < (now - (7 * 24 * 60 * 60))
            )) | 
            .[].id
          ')
          
          # Delete old caches
          set +e
          echo "Deleting old caches..."
          for cacheKey in $cacheKeysToDelete; do
            echo "Deleting cache $cacheKey"
            gh cache delete $cacheKey || true
          done
          echo "Cache cleanup completed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }} 