name: Cache

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  cache:
    name: Setup Cache
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        run: |
          rustup default stable
      
      - name: Setup Cargo Registry Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: shared-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: shared-cargo-
      
      - name: Setup Target Cache
        uses: actions/cache@v4
        with:
          path: target
          key: shared-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: shared-target-
      
      - name: Cache Setup Complete
        run: echo "Cache setup completed" 