---
# GNU Affero General Public License v3.0 or later
# See LICENSE or https://www.gnu.org/licenses/agpl.txt
name: CI
"on":
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  packages: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: |-
          gh release download --repo t-c-l-o-u-d/vlint --pattern '*x86_64-linux' --output /tmp/vlint
          sudo install -m755 /tmp/vlint /usr/local/bin/vlint
        env:
          GH_TOKEN: ${{ github.token }}
      - run: vlint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: cargo build --release
