# GNU Affero General Public License v3.0 or later (see LICENSE or https://www.gnu.org/licenses/agpl.txt)
# Publish workflow

name: Publish

on:
  workflow_call:

jobs:
  download:
    name: Download Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ovc-*
  publish:
    name: Publish Release
    uses: softprops/action-gh-release@v2
    with:
        files: ovc-*
